spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml
